export namespace COMMON {
  export enum API_ERRORS {
    INTERNAL_SERVER_ERROR="INTERNAL_SERVER_ERROR",
    NOT_FOUND="NOT_FOUND",
    BAD_REQUEST="BAD_REQUEST",
    UNAUTHORIZED="UNAUTHORIZED",
    LIMIT_IS_NOT_VALID="LIMIT_IS_NOT_VALID",
    OFFSET_IS_NOT_VALID="OFFSET_IS_NOT_VALID",
  }
}
